
export const cuisineList = [
    "Regular Veg Thali",
"Mini Thali",
"Premium Thali",
"Diet Thali",
"Jain Thali",
"South Indian Thali",
"Non-Veg Thali",
"Maharashtrian Thali",
"Gujarati Thali",
"Punjabi Thali",
"Bengali Thali",
"Rajasthani Thali",
"Malvani Thali",
"Kerala Thali",
"Tamil Nadu Thali",
"Andhra Thali",
"Sindhi Thali",
"Bohri Thali",
"Konkani Thali",
"High-Protein Thali",
"Low-Carb Thali",
"Diabetic-Friendly Thali",
"Millet-Based Thali",
"Vegan Thali",
"Festive Special Thali",
"Kathiyawadi Thali",
"Hyderabadi Thali",
"North Indian Thali",
"Satvik Thali",
"Fusion Thali",
  ];
  